### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Boso101** [utilForever/RosettaStone#124]
Hi I have noticed there has been a lot of progress lately, was wondering if it is planned or currently has the capability to play a game with proper hearthstone graphics

**Comment by Boso101** [comment]
and if there is a discord i'd be interested in joining

**Comment by utilForever** [comment]
Hi, I made Hearthstone++ GUI program a few months ago. However, It works 'login' and 'create account' scene only. Currently, we focus on card implementation. Once the basic card implementation is finished, I'll resume GUI program development that we have stopped for a while. Thanks.

**Comment by utilForever** [comment]
And we'll make a public discord channel soon, so please wait. :wave:

**Comment by Boso101** [comment]
Sounds good! :D. I am interested in helping out with some card implementations later down the line, especially adventure related cards. With the gui however,  I can certainly help out. Currently, would it be fine for me to compile a bunch of basic card pngs with blank cost/attk and health?
