### ISSUE TITLE
Sabberstone, maybe some coop possible.

### ISSUE THREAD

**Issue by darkfriend77** [utilForever/RosettaStone#128]
Hi,

I'm the dev from https://github.com/HearthSim/SabberStone

maybee you're interested in having some talk, about hearthstone simulator.

**Comment by utilForever** [comment]
Hi, Nice to meet you. :)
What would you like to talk about?

**Comment by utilForever** [comment]
@darkfriend77 Just for remind. :)

**Comment by darkfriend77** [comment]
**Basic & Classic**

    100% Basic (142 Cards)
    100%% Classic (239 Cards)
    70% Hall of Fame (10 Cards)

**Adventures**

    100% Blackrock Mountain (31 Cards)
    100% One Night in Karazhan (45 Cards)
    93% The League of Explorers (45 Cards) (needs to be upgraded to new system)

**Expensions**

    93% The Witchwood (135 Cards)
    100% Kobolds and Catacombs (135 Cards)
    100% Knights of the Frozen Throne (135 Cards)
    100% Journey to Un'Goro (135 cards)
    91% The Grand Tournament (132 Cards) (needs to be upgraded to new system)
    100% Whispers of the Old Gods (134 Cards)
    100% Mean Streets of Gadgetzan (132 Cards)
    79% Goblins vs Gnomes (123 cards)
    100% Curse of Naxxramas (30 cards)

**Comment by utilForever** [comment]
Thank you for your suggestion.
I already knew there was a Sabberstone project at the time of this project. I have been able to leverage the existing projects, but I started with the idea of making a project that can take advantage of the C++ language and handle it with high performance. If we can help Sabberstone, we will work together. However, this project will continue. Thank you.
