### ISSUE TITLE
Add code quality tool (LGTM)

### ISSUE THREAD

**Issue by utilForever** [utilForever/RosettaStone#138]
Software is critical in all aspects of our lives. From entertainment, shopping and dating, to business-critical systems and software where human lives are at stake. And yet preventable bugs are all too frequent. LGTM seeks to address this situation.

- References
    - https://lgtm.com/help/lgtm/lgtm.yml-configuration-file#example-lgtm.yml-file
    - https://github.com/rneatherway/turbo-octo-enigma/blob/master/.lgtm.yml

**Comment by sjvs** [comment]
PR open and ready to go: https://github.com/utilForever/Hearthstonepp/pull/139 :slightly_smiling_face:

**Comment by utilForever** [comment]
@sjvs Could you check this? https://lgtm.com/projects/g/utilForever/Hearthstonepp/
Still, there are many alerts in third-party libraries.

**Comment by sjvs** [comment]
LGTM is currently crunching the latest revisions of Heartstonepp. This could take a few moments, but the new results should appear soon!

**Comment by utilForever** [comment]
@sjvs Alright. Thanks. 😆

**Comment by sjvs** [comment]
For example, your code quality badges have already been updated with the new stats:

![badges](https://user-images.githubusercontent.com/5082246/44791772-4d00a000-ab9a-11e8-8dc9-42ad52171d92.png)

Quality grade A: congratulations!

**Comment by utilForever** [comment]
@sjvs Thanks, lol. I should fix my code. 🍡

**Comment by utilForever** [comment]
@sjvs I'll use LGTM to another projects. For example, https://github.com/utilForever/CubbyFlow-v0

**Comment by sjvs** [comment]
Great — have fun! You can add your own projects from the dashboard: https://lgtm.com/dashboard. I think LGTM is actually already in the process of doing a first scan of your public repos as we speak, so all of them should appear soon.

Give me a shout if you need help with anything.

**Comment by sjvs** [comment]
That's a cool project, by the way! Loving the images here: https://utilforever.github.io/CubbyFlow-v0/Examples/

**Comment by sjvs** [comment]
First results for CubbyFlow-0 are available on LGTM.com: https://github.com/utilForever/CubbyFlow-v0/pull/56 :slightly_smiling_face:
