### ISSUE TITLE
required install python, before to build hearthstonepp?

### ISSUE THREAD

**Issue by ssapo** [utilForever/RosettaStone#197]
i using win10,
i clone this repo and watch and followed "Quick Start"

but ALL_BUILD was failed because hearthstonepp_header_gen_py's compile error with logs.

1>Generating ../../../Includes/hspp.hpp
1>'python'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
1>배치 파일이 아닙니다.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe"이(가) 종료되었습니다(코드: 9009).
1>"hearthstonepp_header_gen_py.vcxproj" 프로젝트를 빌드했습니다. - 실패

How can fix it?

**Comment by utilForever** [comment]
Oh, we use python due to header file generation. We'll change that this flag makes optional. Thanks.

**Comment by ssapo** [comment]
Thanks! i fixed it by installing python.
