### ISSUE TITLE
Is there a better way to see json format in vs 2017?

### ISSUE THREAD

**Issue by hankyulhyun** [utilForever/RosettaStone#199]
When i see resources file such as /Resources/cards.json,
all the texts lie with one line like this screenshot

![image](https://user-images.githubusercontent.com/25781932/54205097-001e5e80-4519-11e9-87fd-1f33b710518f.png)

So i tried to find by card name in json file,
but vs2017 just announce me that found the card in line number 1.

Is there a better way to see json format in vs2017? (15.9.4)
Thanks.

**Comment by utilForever** [comment]
In Visual Studio code, 'Prettify JSON' extension makes JSON format prettify.
![image](https://user-images.githubusercontent.com/5622661/54493419-3aba3980-4913-11e9-804f-fd2fa333e616.png)
