### ISSUE TITLE
New entity type needed?

### ISSUE THREAD

**Issue by hankyulhyun** [utilForever/RosettaStone#201]
Hello :)

I found logical error in my PR for "Fan of Knives" card.
In my PR, the card deals damages to enemy minions and "hero"
(EntityType::ENEMIES)
so, I think that make new entity type for only enemy field minions.

in addition, I see some distinguishing cards and find some issues

1. "Mad Bomber" card
 - need new entity type for random characters and minions?
2. "Flamewaker" card
 - need new entity type for random op character and op minions
 - how to know cur players card playing..?
3. "Archmage Antonidas" card
 - how to know cur players 'spell' card playing..?

Thanks =)

--------------

안녕하세요

영어로 작성하긴 했지만 실력이 좋지 않아 한글로도 함께 남기겠습니다
한글로 함께 작성하는것을 원치 않으신다면 말씀 주세요 바로 수정할게요 =)

칼날부채 카드로 PR을 올렸었는데 논리적 오류가 있었습니다
EntityType::ENEMIES 로 데미지를 가했을 때 상대 영웅에게도 데미지가 들어가게 되어있네요
상대방 하수인만을 특정하는 EntityType이 필요하지 않을까 생각됩니다
(같은 생각이시라면 확인 후 추가 PR 올리겠습니다)

추가로 특징을 가지고 있는 카드를 보고 있는 중에 entitytype 관련 궁금증이 있습니다.

1. 정신나간 폭격수 카드
 - 무작위의 케릭터를 지칭하는 entitytype 이 필요할까요?
2. 불꽃꼬리전사 카드
 - 상대방 무작위의 케릭터를 지칭하는 entitytype 이 필요할까요?
 - 카드를 필드에 낸 후에 이 카드가 사용자가 카드를 내는 것을 어떻게 알 수 있을까요
3. 대마법사 안토니다스 카드
 - 카드를 필드에 낸 후에 사용자가 내는 spell 카드를 어떻게 알 수 있을까요

소스 보면서 많이 배우고 있습니다
항상 감사합니다 =)

**Comment by utilForever** [comment]
안녕하세요, 한국어가 편하실 것 같아 답변 남깁니다.

상대방 하수인만을 지정하는 ENEMY_FIELD라는 EntityType이 있긴 합니다.
다만, IncludeTask에 ENEMY_FIELD일 때의 케이스를 추가하지 않았네요.
이 부분을 추가하면 해결될 듯 합니다. IncludeTask.cpp를 참고하시기 바랍니다.

정신나간 폭격수는 무작위의 캐릭터, 불꽃 꼬리 전사는 무작위의 상대방 캐릭터를 대상으로 합니다만, 무작위일 때도 차이는 있습니다. 무작위 적 하수인, 무작위 하수인, 무작위 캐릭터 등 다양하지요. 무작위를 대상하는 EntityType을 추가하기 보다는 무작위인지 아닌지 여부를 확인하기 위한 bool 타입의 인자를 추가하는게 좋다는 생각입니다.

불꽃 꼬리 전사나 대마법사 안토니다스 카드를 필드에 낸 후에 사용자가 어떤 카드를 낼 때마다 동작할 수 있게 만드려면 트리거를 구현해야 합니다. 이 부분은 아직 구현되지 않았습니다. 현재 게임 구조를 리팩토링하고 있는데 그 이후에 작업하지 않을까 싶습니다.
