### ISSUE TITLE
Encode/decode Hearthstone's deck code

### ISSUE THREAD

**Issue by utilForever** [utilForever/RosettaStone#204]
Deck Importing or Deck Sharing is a feature in Hearthstone, which allows decks to be easily shared with everyone using deck strings.

If your deck is already full, when you select the Hero portrait at the top of a deck list in the collection manager, you’ll see a Copy button. Press that button and your deck list will be copied to your clipboard. If you paste your deck list into a text document, it will look like this:

![image](https://user-images.githubusercontent.com/5622661/54608304-c8bd2e00-4a93-11e9-9a44-7c6ebd7f5be3.png)

The highlighted code near the bottom contains all the deck information, making it easier to share a deck list with friends in chat or social media. When you go to create a new deck, Hearthstone will “know” when you’ve got a valid deck list on your clipboard, so you’ll be asked if you’d like to create a new deck with the one you’ve got copied, and it will build the deck based on the code. This can also be used for Tavern Brawl decks.

If you don’t have all the cards a deck requires, it works just like a deck recipe. Any cards you don’t already own will appear insubstantial and you can select them for suggested replacements.
The encoding used is in Base 64.

**Comment by utilForever** [comment]
Example 1:
```
### Even Shaman - Standard Meta Snapshot - May 18, 2018
# Class: Shaman
# Format: Standard
# Year of the Raven
#
# 1x (2) Acidic Swamp Ooze
# 2x (2) Dire Wolf Alpha
# 2x (2) Earthen Might
# 2x (2) Flametongue Totem
# 2x (2) Knife Juggler
# 2x (2) Murkspark Eel
# 2x (2) Primalfin Totem
# 2x (2) Vicious Scalehide
# 2x (4) Corpsetaker
# 2x (4) Hex
# 2x (4) Saronite Chain Gang
# 2x (6) Argent Commander
# 1x (6) Fire Elemental
# 1x (6) Genn Greymane
# 1x (8) Al'Akir the Windlord
# 1x (8) Hagatha the Witch
# 1x (8) The Lich King
# 2x (10) Sea Giant
#
AAECAfe5AgaKB70BzfQCIKfuAsLOAgzZB7DwAvAHsQiU7wKRwQL27AKW6AL+BZvLApkC0wEA #
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone
```

**Comment by utilForever** [comment]
Example 2:
```
### control
# Class: Mage
# Format: Wild
#
# 2x (1) Arcane Artificer
# 1x (2) Acidic Swamp Ooze
# 2x (2) Plated Beetle
# 2x (2) Raven Familiar
# 1x (3) Acolyte of Pain
# 2x (3) Stonehill Defender
# 2x (3) Voodoo Doll
# 2x (4) Arcane Keysmith
# 2x (4) Polymorph
# 2x (5) Dragon's Fury
# 2x (5) Rotten Applebaum
# 2x (6) Blizzard
# 2x (6) Meteor
# 1x (6) Skulking Geist
# 1x (7) Baron Geddon
# 1x (7) Flamestrike
# 1x (8) Sindragosa
# 1x (8) The Lich King
# 1x (9) Frost Lich Jaina
# 
AAEBAf0ECNACigfsB/sMoM4Cws4Cm9MC8tMCC03JA5vCApbHAtXhAtfhApbkAurmAr7sArfxAsXzAgA= # 
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone
```

**Comment by shinoi2** [comment]
https://github.com/HearthSim/python-hearthstone/wiki/Deck-Strings
It will helpful.
