### ISSUE TITLE
Card search result shows nothing

### ISSUE THREAD

**Issue by saitouena** [utilForever/RosettaStone#239]
I tried RosettaConsole.
```cpp
========================================
1. Search Card
2. Manage Deck
3. Simulate Game
4. Leave
========================================
Select: 1
========================================
              Search Card!              
========================================
If you want to get help, type -h or --help.
Command > 
========================================
             Search Result!             
========================================
There are no cards matching your search condition.
Command > -n "Novice Engineer"
========================================
             Search Result!             
========================================
There are no cards matching your search condition.

```
I expected to get all cards when I just pressed the enter.  It seems this https://github.com/utilForever/RosettaStone/blob/e0f2dbccf4df33caae668af29304cceadbc021fb/Extensions/RosettaConsole/Console.cpp#L621-L622 doesn't works correctly. I added a console output in inner loop, but it outputs nothing. Maybe CardLoader doesn't works for now.

Is this related? https://github.com/utilForever/RosettaStone/issues/205

**Comment by utilForever** [comment]
Thanks for reporting issue. I'll investigate it. :)

**Comment by utilForever** [comment]
This issue is now fixed on master.
