### ISSUE TITLE
Minion is not destroyed at SetDamage()

### ISSUE THREAD

**Issue by cyj0711** [utilForever/RosettaStone#257]
When I tested a minion card that has Deathrattle, I used SetDamage() function to kill the minion. But the minion wasn't destroyed and sill exist at field with under 0 health.

Here is example code.
This is the code of Abomination(5 cost, 4 atk, 4 hp), minion thas has Deathrattle:Deal 2 damage to ALL characters.
i used SetDamage(5) to try destroying the Abomination.

    TEST(NeutralExpert1Test, EX1_097_Abomination)
    {
        GameConfig config;
        config.player1Class = CardClass::WARRIOR;
        config.player2Class = CardClass::MAGE;
        config.startPlayer = PlayerType::PLAYER1;
        config.doFillDecks = true;
        config.autoRun = false;
    
        Game game(config);
        game.StartGame();
        game.ProcessUntil(Step::MAIN_START);
    
        Player& curPlayer = game.GetCurrentPlayer();
        Player& opPlayer = game.GetOpponentPlayer();
        curPlayer.SetTotalMana(10);
        curPlayer.SetUsedMana(0);
        opPlayer.SetTotalMana(10);
        opPlayer.SetUsedMana(0);
    
        auto& curField = curPlayer.GetField();
        auto& opField = opPlayer.GetField();
    
        const auto card1 = Generic::DrawCard(
            curPlayer, Cards::GetInstance().FindCardByName("Abomination"));
        const auto card2 = Generic::DrawCard(
            curPlayer, Cards::GetInstance().FindCardByName("Oasis Snapjaw"));
        const auto card3 = Generic::DrawCard(
            opPlayer, Cards::GetInstance().FindCardByName("Acidic Swamp Ooze"));
    
        game.Process(curPlayer, PlayCardTask::Minion(card1));
        game.Process(curPlayer, PlayCardTask::Minion(card2));
    
        game.Process(curPlayer, EndTurnTask());
        game.ProcessUntil(Step::MAIN_START);
    
       game.Process(opPlayer, PlayCardTask::Minion(card3));
    
        curField.GetMinion(0)->SetDamage(5);
        EXPECT_EQ(curPlayer.GetHero()->GetHealth(), 28);
        EXPECT_EQ(curField.GetNumOfMinions(), 1u);
        EXPECT_EQ(curField.GetMinion(0)->GetHealth(), 5);
        EXPECT_EQ(opPlayer.GetHero()->GetHealth(), 28);
        EXPECT_EQ(opField.GetNumOfMinions(), 0u);
    }

**Comment by utilForever** [comment]
Thanks! I'll check and fix this issue soon.

**Comment by utilForever** [comment]
It's not a bug. You should use not `SetDamage()` but `DamageTask`.
`SetDamage()` don't process destroy logic. Closed.
