### ISSUE TITLE
EX1_383 'Tirion Fordring' calls grave function twice when the card destroyed

### ISSUE THREAD

**Issue by cyj0711** [utilForever/RosettaStone#266]
EX1_383 'Tirion Fordring' : Divine Shield,Taunt, Deathrattle: Equip a 5/3 Ashbringer.
when i tested this card, the test was crashed when 'Tirion Fordring' I summoned be destroyed by enemy minions because grave function called twice at the minion dead, and equiping the weapon.
here is the source code i used

    void Expert1CardsGen::AddPaladin(std::map<std::string, Power>& cards)
    {
        Power power;
    
        // --------------------------------------- MINION - PALADIN
        // [EX1_383] Tirion Fordring - COST:8 [ATK:6/HP:6]
        // - Faction: Neutral, Set: Expert1, Rarity: Legendary
        // --------------------------------------------------------
        // Text: <b><b>Divine Shield</b>,</b> <b>Taunt</b>
        //       <b>Deathrattle:</b> Equip a 5/3 Ashbringer.
        // --------------------------------------------------------
        // GameTag:
        // - ELITE = 1
        // _ DIVINE SHIELD = 1
        // - TAUNT = 1
        // - DEATHRATTLE = 1
        // --------------------------------------------------------
        power.ClearData();
        power.AddDeathrattleTask(new WeaponTask("EX1_383t"));
        cards.emplace("EX1_383", power);
    }

    void Expert1CardsGen::AddPaladinNonCollect(std::map<std::string, Power>& cards)
    {
        Power power;
    
        // --------------------------------------- WEAPON - PALADIN
        // [EX1_383t] Ashbringer (*) - COST:5 [ATK:5/HP:0]
        // - Faction: Neutral, Set: Expert1
        // --------------------------------------------------------
        // GameTag:
        // - ELITE = 1
        // - DURABILITY = 3
        // --------------------------------------------------------
        power.ClearData();
        power.AddPowerTask(nullptr);
        cards.emplace("EX1_383t", power);
    }

these two codes are Implementation of 'Tirion Fordring' and 'Ashbringer', the weapon that Tirion Fordring summons when he dead.

    // --------------------------------------- MINION - PALADIN
    // [EX1_383] Tirion Fordring - COST:8 [ATK:6/HP:6]
    // - Faction: Neutral, Set: Expert1, Rarity: Legendary
    // --------------------------------------------------------
    // Text: <b><b>Divine Shield</b>,</b> <b>Taunt</b>
    //       <b>Deathrattle:</b> Equip a 5/3 Ashbringer.
    // --------------------------------------------------------
    // GameTag:
    // - ELITE = 1
    // _ DIVINE SHIELD = 1
    // - TAUNT = 1
    // - DEATHRATTLE = 1
    // --------------------------------------------------------
    TEST(PaladinExpert1Test, EX1_383_TirionFordring)
    {
        GameConfig config;
        config.player1Class = CardClass::PALADIN;
        config.player2Class = CardClass::MAGE;
        config.startPlayer = PlayerType::PLAYER1;
        config.doFillDecks = true;
        config.autoRun = false;
    
        Game game(config);
        game.StartGame();
        game.ProcessUntil(Step::MAIN_START);
    
        Player& curPlayer = game.GetCurrentPlayer();
        Player& opPlayer = game.GetOpponentPlayer();
        curPlayer.SetTotalMana(10);
        curPlayer.SetUsedMana(0);
        opPlayer.SetTotalMana(10);
        opPlayer.SetUsedMana(0);
    
        auto& curField = curPlayer.GetFieldZone();
        auto& opField = opPlayer.GetFieldZone();
    
        const auto card1 = Generic::DrawCard(
            curPlayer, Cards::GetInstance().FindCardByName("Tirion Fordring"));
        const auto card2 = Generic::DrawCard(
            opPlayer, Cards::GetInstance().FindCardByName("Wolfrider"));
        const auto card3 = Generic::DrawCard(
            opPlayer, Cards::GetInstance().FindCardByName("Wolfrider"));
        const auto card4 = Generic::DrawCard(
            opPlayer, Cards::GetInstance().FindCardByName("Wolfrider"));
    
        game.Process(curPlayer, PlayCardTask::Minion(card1));
        EXPECT_EQ(curPlayer.GetHero()->HasWeapon(), false);
        EXPECT_EQ(curField.GetCount(), 1);
        EXPECT_EQ(curField[0]->GetAttack(), 6);
        EXPECT_EQ(curField[0]->GetHealth(), 6);
        
        Task::Run(curPlayer, EndTurnTask());
        game.ProcessUntil(Step::MAIN_START);
    
        game.Process(opPlayer, PlayCardTask::Minion(card2));
        game.Process(opPlayer, PlayCardTask::Minion(card3));
        game.Process(opPlayer, PlayCardTask::Minion(card4));
        EXPECT_EQ(opField.GetCount(), 3);
    
        game.Process(opPlayer, AttackTask(card2, card1));
        EXPECT_EQ(curField[0]->GetHealth(), 6);
    
        game.Process(opPlayer, AttackTask(card3, card1));
        EXPECT_EQ(curField[0]->GetHealth(), 3);
    
        game.Process(opPlayer, AttackTask(card4, card1));
        /*EXPECT_EQ(curField.GetCount(), 0);
        EXPECT_EQ(curPlayer.GetHero()->HasWeapon(), true);
        EXPECT_EQ(curPlayer.GetHero()->weapon->GetAttack(), 5);
        EXPECT_EQ(curPlayer.GetHero()->weapon->GetDurability(), 3);
        EXPECT_EQ(opPlayer.GetHero()->GetHealth(), 30);
    
        Task::Run(opPlayer, EndTurnTask());
        game.ProcessUntil(Step::MAIN_START);
    
        game.Process(curPlayer,
                     AttackTask(curPlayer.GetHero(), opPlayer.GetHero()));
        EXPECT_EQ(opPlayer.GetHero()->GetHealth(), 25);
        EXPECT_EQ(curPlayer.GetHero()->weapon->GetDurability(), 2);*/
    }

this code is a test scenario code for Tirion Fordring.
I wrote comments the codes that be executed after crash.
"game.Process(opPlayer, AttackTask(card4, card1));" this code make crash when Tirion Fordring dead.

**Comment by utilForever** [comment]
I checked this bug. I'll fix it ASAP. Thanks.
