### ISSUE TITLE
How can I generate card comment like this?

### ISSUE THREAD

**Issue by shinoi2** [utilForever/RosettaStone#310]
// ------------------------------------------ SPELL - DRUID
    // [EX1_154] Wrath - COST:2
    // - Faction: Neutral, Set: Expert1, Rarity: Common
    // --------------------------------------------------------
    // Text: <b>Choose One -</b>
    //       Deal $3 damage to a minion; or $1 damage
    //       and draw a card.
    // --------------------------------------------------------
    // GameTag:
    // - CHOOSE_ONE = 1
    // --------------------------------------------------------
    // PlayReq:
    // - REQ_TARGET_TO_PLAY = 0
    // - REQ_MINION_TARGET = 0
    // --------------------------------------------------------

**Comment by utilForever** [comment]
This card comment is referenced by cards.json and Hearthstone card data. :)

**Comment by shinoi2** [comment]
Can you provide a tool that transform from json to comment?

**Comment by scottsuk0306** [comment]
Currently, card comment can be generated by CardCommentGen.py at Scripts folder. Please refer to the guideline here. (#466)
