### ISSUE TITLE
RosettaConsole 'Manage Deck - Add Card(s)' -n option doesn't work

### ISSUE THREAD

**Issue by JawsKim** [utilForever/RosettaStone#451]
In Search Card
```
========================================
1. Search Card
2. Manage Deck
3. Simulate Game
4. Leave
========================================
Select: 1
========================================
              Search Card!              
========================================
If you want to get help, type -h or --help.
Command > -n "Chaos"
========================================
             Search Result!             
========================================
1. Chaos Strike (BT_035) 
2. Chaos Nova (BT_235) 
3. Chaos Gazer (YOD_027) 

```

In Add Card(s)
```
========================================
1. Add Card(s)
2. Delete Card(s)
3. Back
========================================
What do you want to do? 1
========================================
              Search Card!              
========================================
If you want to get help, type -h or --help.
Command > -n "Chaos"
========================================
             Search Result!             
========================================
There are no cards matching your search condition.
```

A similar problem was found with #449.

My environment is ubuntu 20.04, gcc 9.3.0, cmake 3.16.3.

**Comment by beuoon** [comment]
A card which can be added to the deck is only that has attribute 'Collectable' and class of card equals class of deck or 'NEUTRAL'.

The class of both 'Chaos Strike' and 'Chaos Nova' is 'DEMONHUNTER'.
And the class of 'Chaos Gazer' is 'WARLOCK'.

Maybe your deck's class is not 'WARLOCK' and 'DEMONHUNTER'.
So nothing was searched.

When the deck's class is 'WARLOCK', searched result is the same with follows.
```
========================================
1. Druid
2. Hunter
3. Mage
4. Paladin
5. Priest
6. Rogue
7. Shaman
8. Warlock
9. Warrior

========================================
What's your player class? 8
========================================
1. Add Card(s)
2. Delete Card(s)
3. Back
========================================
What do you want to do? 1
========================================
              Search Card!
========================================
If you want to get help, type -h or --help.
Command > -n "Chaos"
========================================
             Search Result!
========================================
1. Chaos Gazer (YOD_027)
Select:
```

**Comment by JinDDeok** [comment]
> A card which can be added to the deck is only that has attribute 'Collectable' and class of card equals class of deck or 'NEUTRAL'.
> 
> The class of both 'Chaos Strike' and 'Chaos Nova' is 'DEMONHUNTER'.
> And the class of 'Chaos Gazer' is 'WARLOCK'.
> 
> Maybe your deck's class is not 'WARLOCK' and 'DEMONHUNTER'.
> So nothing was searched.
> 
> When the deck's class is 'WARLOCK', searched result is the same with follows.
> 
> ```
> ========================================
> 1. Druid
> 2. Hunter
> 3. Mage
> 4. Paladin
> 5. Priest
> 6. Rogue
> 7. Shaman
> 8. Warlock
> 9. Warrior
> 
> ========================================
> What's your player class? 8
> ========================================
> 1. Add Card(s)
> 2. Delete Card(s)
> 3. Back
> ========================================
> What do you want to do? 1
> ========================================
>               Search Card!
> ========================================
> If you want to get help, type -h or --help.
> Command > -n "Chaos"
> ========================================
>              Search Result!
> ========================================
> 1. Chaos Gazer (YOD_027)
> Select:
> ```



> A card which can be added to the deck is only that has attribute 'Collectable' and class of card equals class of deck or 'NEUTRAL'.
> 
> The class of both 'Chaos Strike' and 'Chaos Nova' is 'DEMONHUNTER'.
> And the class of 'Chaos Gazer' is 'WARLOCK'.
> 
> Maybe your deck's class is not 'WARLOCK' and 'DEMONHUNTER'.
> So nothing was searched.
> 
> When the deck's class is 'WARLOCK', searched result is the same with follows.
> 
> ```
> ========================================
> 1. Druid
> 2. Hunter
> 3. Mage
> 4. Paladin
> 5. Priest
> 6. Rogue
> 7. Shaman
> 8. Warlock
> 9. Warrior
> 
> ========================================
> What's your player class? 8
> ========================================
> 1. Add Card(s)
> 2. Delete Card(s)
> 3. Back
> ========================================
> What do you want to do? 1
> ========================================
>               Search Card!
> ========================================
> If you want to get help, type -h or --help.
> Command > -n "Chaos"
> ========================================
>              Search Result!
> ========================================
> 1. Chaos Gazer (YOD_027)
> Select:
> ```

I didn't understand the hearthstone. Thank you :)

**Comment by JinDDeok** [comment]
I didn't understand the hearthstone. Thank you :)

**Comment by utilForever** [comment]
Thanks for the report and the reply.
