### ISSUE TITLE
Question about "AddNeutralNonCollect" card

### ISSUE THREAD

**Issue by hankyul2** [utilForever/RosettaStone#491]
In [Document](https://utilforever.github.io/RosettaStone/doxygen/class_rosetta_stone_1_1_core_cards_gen.html#a80b7946d25ae18a86dd88a541e20db8c) `AddNeutralNonCollect` function is for adding card with power. And as our @utilForever metioned like below, power type is either enchant or token.  
![image](https://user-images.githubusercontent.com/31476895/90716703-87642a00-e2e8-11ea-8e29-70f7e38da07c.png)
My Question is : "Is aura also a card with power?". I am asking this because of comment in [this code](https://github.com/utilForever/RosettaStone/blob/a90c02acc46fe5b32cfa4ae59d8b85dacd8a5cf2/Sources/Rosetta/PlayMode/CardSets/BlackTempleCardsGen.cpp#L2359) The card I linked have aura. And similar case can be found in [here](https://github.com/utilForever/RosettaStone/blob/a90c02acc46fe5b32cfa4ae59d8b85dacd8a5cf2/Sources/Rosetta/PlayMode/CardSets/Expert1CardsGen.cpp#L1531), which does not included in `AddNeutralNonCollect` function.

![atom_LqvEY7y9BS](https://user-images.githubusercontent.com/31476895/90717033-6fd97100-e2e9-11ea-8d6d-d7db680a3405.png)

Is this comment auto created? or Should I have to add a card with aura to this function?

**Comment by utilForever** [comment]
I answered on the Discord channel. Thank you.
